name: Deploy

on:
  schedule:
    - cron: '30 14 * * *'  # 每天太平洋时间凌晨6:30点执行（UTC时间14:30）
  workflow_dispatch:  # 手动触发

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: AutoRead  # 指定环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install certifi==2024.8.30 charset-normalizer==3.4.0 idna==3.10 requests==2.32.3 urllib3==2.2.3

    - name: Run deployment script
      env:
        WXREAD_CURL: ${{ secrets.WXREAD_CURL }}
        READ_NUM: ${{ vars.READ_NUM }}  # 使用 Repository Variables
        PUSH_METHOD: ${{ secrets.PUSH_METHOD }}
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python main.py
